[git-shift-time] Added a utility to shift the timestamp of git commits.

diff --git a/git-same-sig-time b/git-same-sig-time
--- a/git-same-sig-time
+++ b/git-same-sig-time
@@ -12,6 +12,12 @@
 #                                                                           #
 #############################################################################
 
+if ! command -v faketime &> /dev/null
+then
+    echo "'faketime' could not be found. Please install it first."
+    exit
+fi
+
 git pretty -1 > /dev/null 2>&1
 if [ "$?" -eq 1 ]; then
     echo "Error: You need \`git pretty\` installed. Add this to your ~/.gitconfig:"
